# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cal.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(486, 448)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QMainWindow {\n"
"    background-color: #E0E0E0;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(60, 20, 351, 381))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gridLayoutWidget.sizePolicy().hasHeightForWidth())
        self.gridLayoutWidget.setSizePolicy(sizePolicy)
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_19 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgb(0, 191, 255), stop:1 rgb(0, 128, 255));\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    font: 75 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 150, 220);\n"
"}\n"
"")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 5, 0, 1, 2)
        self.push_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_6.sizePolicy().hasHeightForWidth())
        self.push_6.setSizePolicy(sizePolicy)
        self.push_6.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgb(0, 191, 255), stop:1 rgb(0, 128, 255));\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    font: 75 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 150, 220);\n"
"}\n"
"\n"
"")
        self.push_6.setObjectName("push_6")
        self.gridLayout.addWidget(self.push_6, 3, 2, 1, 1)
        self.push_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_2.sizePolicy().hasHeightForWidth())
        self.push_2.setSizePolicy(sizePolicy)
        self.push_2.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgb(0, 191, 255), stop:1 rgb(0, 128, 255));\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    font: 75 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 150, 220);\n"
"}\n"
"")
        self.push_2.setObjectName("push_2")
        self.gridLayout.addWidget(self.push_2, 2, 1, 1, 1)
        self.push_del = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_del.sizePolicy().hasHeightForWidth())
        self.push_del.setSizePolicy(sizePolicy)
        self.push_del.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(204, 255, 0);\n"
"    border-radius: 20px;\n"
"    font: 600 17pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80);\n"
"    color: rgb(255, 255, 102);\n"
"}\n"
"")
        self.push_del.setObjectName("push_del")
        self.gridLayout.addWidget(self.push_del, 1, 2, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(204, 255, 0);\n"
"    border-radius: 20px;\n"
"    font: 600 17pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80);\n"
"    color: rgb(255, 255, 102);\n"
"}\n"
"")
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 1, 3, 1, 1)
        self.push_dot = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_dot.sizePolicy().hasHeightForWidth())
        self.push_dot.setSizePolicy(sizePolicy)
        self.push_dot.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(204, 255, 0);\n"
"    border-radius: 20px;\n"
"    font: 600 17pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80);\n"
"    color: rgb(255, 255, 102);\n"
"}\n"
"")
        self.push_dot.setObjectName("push_dot")
        self.gridLayout.addWidget(self.push_dot, 5, 2, 1, 1)
        self.push_equal = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_equal.sizePolicy().hasHeightForWidth())
        self.push_equal.setSizePolicy(sizePolicy)
        self.push_equal.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(204, 255, 0);\n"
"    border-radius: 20px;\n"
"    font: 600 17pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80);\n"
"    color: rgb(255, 255, 102);\n"
"}\n"
"")
        self.push_equal.setObjectName("push_equal")
        self.gridLayout.addWidget(self.push_equal, 5, 3, 1, 1)
        self.psuh_multi = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.psuh_multi.sizePolicy().hasHeightForWidth())
        self.psuh_multi.setSizePolicy(sizePolicy)
        self.psuh_multi.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(204, 255, 0);\n"
"    border-radius: 20px;\n"
"    font: 600 17pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80);\n"
"    color: rgb(255, 255, 102);\n"
"}\n"
"")
        self.psuh_multi.setObjectName("psuh_multi")
        self.gridLayout.addWidget(self.psuh_multi, 3, 3, 1, 1)
        self.push_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_1.sizePolicy().hasHeightForWidth())
        self.push_1.setSizePolicy(sizePolicy)
        self.push_1.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgb(0, 191, 255), stop:1 rgb(0, 128, 255));\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    font: 75 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 150, 220);\n"
"}\n"
"")
        self.push_1.setObjectName("push_1")
        self.gridLayout.addWidget(self.push_1, 2, 0, 1, 1)
        self.push_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_4.sizePolicy().hasHeightForWidth())
        self.push_4.setSizePolicy(sizePolicy)
        self.push_4.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgb(0, 191, 255), stop:1 rgb(0, 128, 255));\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    font: 75 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 150, 220);\n"
"}\n"
"")
        self.push_4.setObjectName("push_4")
        self.gridLayout.addWidget(self.push_4, 3, 0, 1, 1)
        self.push_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_5.sizePolicy().hasHeightForWidth())
        self.push_5.setSizePolicy(sizePolicy)
        self.push_5.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgb(0, 191, 255), stop:1 rgb(0, 128, 255));\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    font: 75 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 150, 220);\n"
"}\n"
"")
        self.push_5.setObjectName("push_5")
        self.gridLayout.addWidget(self.push_5, 3, 1, 1, 1)
        self.push_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_9.sizePolicy().hasHeightForWidth())
        self.push_9.setSizePolicy(sizePolicy)
        self.push_9.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgb(0, 191, 255), stop:1 rgb(0, 128, 255));\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    font: 75 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 150, 220);\n"
"}\n"
"\n"
"")
        self.push_9.setObjectName("push_9")
        self.gridLayout.addWidget(self.push_9, 4, 2, 1, 1)
        self.push_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_7.sizePolicy().hasHeightForWidth())
        self.push_7.setSizePolicy(sizePolicy)
        self.push_7.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgb(0, 191, 255), stop:1 rgb(0, 128, 255));\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    font: 75 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 150, 220);\n"
"}\n"
"")
        self.push_7.setObjectName("push_7")
        self.gridLayout.addWidget(self.push_7, 4, 0, 1, 1)
        self.push_div = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_div.sizePolicy().hasHeightForWidth())
        self.push_div.setSizePolicy(sizePolicy)
        self.push_div.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(204, 255, 0);\n"
"    border-radius: 20px;\n"
"    font: 600 17pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80);\n"
"    color: rgb(255, 255, 102);\n"
"}\n"
"")
        self.push_div.setObjectName("push_div")
        self.gridLayout.addWidget(self.push_div, 4, 3, 1, 1)
        self.push_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_3.sizePolicy().hasHeightForWidth())
        self.push_3.setSizePolicy(sizePolicy)
        self.push_3.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgb(0, 191, 255), stop:1 rgb(0, 128, 255));\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    font: 75 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 150, 220);\n"
"}\n"
"")
        self.push_3.setObjectName("push_3")
        self.gridLayout.addWidget(self.push_3, 2, 2, 1, 1)
        self.push_minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_minus.sizePolicy().hasHeightForWidth())
        self.push_minus.setSizePolicy(sizePolicy)
        self.push_minus.setStyleSheet("QPushButton {\n"
"    background-color: rgb(50, 50, 50);\n"
"    color: rgb(204, 255, 0);\n"
"    border-radius: 20px;\n"
"    font: 600 17pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(80, 80, 80);\n"
"    color: rgb(255, 255, 102);\n"
"}\n"
"")
        self.push_minus.setObjectName("push_minus")
        self.gridLayout.addWidget(self.push_minus, 2, 3, 1, 1)
        self.push_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_8.sizePolicy().hasHeightForWidth())
        self.push_8.setSizePolicy(sizePolicy)
        self.push_8.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgb(0, 191, 255), stop:1 rgb(0, 128, 255));\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    font: 75 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 150, 220);\n"
"}\n"
"")
        self.push_8.setObjectName("push_8")
        self.gridLayout.addWidget(self.push_8, 4, 1, 1, 1)
        self.push_clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_clear.sizePolicy().hasHeightForWidth())
        self.push_clear.setSizePolicy(sizePolicy)
        self.push_clear.setStyleSheet("QPushButton {\n"
"    background-color: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"        stop:0 rgb(0, 191, 255), stop:1 rgb(0, 128, 255));\n"
"    color: white;\n"
"    border-radius: 30px;\n"
"    font: 75 18pt \"Segoe UI\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 150, 220);\n"
"}\n"
"")
        self.push_clear.setObjectName("push_clear")
        self.gridLayout.addWidget(self.push_clear, 1, 0, 1, 2)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"font: 75 28pt \"MS Shell Dlg 2\";\n"
"font: 75 24pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 486, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "calculator"))
        self.pushButton_19.setText(_translate("MainWindow", "0"))
        self.push_6.setText(_translate("MainWindow", "6"))
        self.push_2.setText(_translate("MainWindow", "2"))
        self.push_del.setText(_translate("MainWindow", "Del"))
        self.pushButton_10.setText(_translate("MainWindow", "+"))
        self.push_dot.setText(_translate("MainWindow", "."))
        self.push_equal.setText(_translate("MainWindow", "="))
        self.psuh_multi.setText(_translate("MainWindow", "*"))
        self.push_1.setText(_translate("MainWindow", "1"))
        self.push_4.setText(_translate("MainWindow", "4"))
        self.push_5.setText(_translate("MainWindow", "5"))
        self.push_9.setText(_translate("MainWindow", "9"))
        self.push_7.setText(_translate("MainWindow", "7"))
        self.push_div.setText(_translate("MainWindow", "/"))
        self.push_3.setText(_translate("MainWindow", "3"))
        self.push_minus.setText(_translate("MainWindow", "-"))
        self.push_8.setText(_translate("MainWindow", "8"))
        self.push_clear.setText(_translate("MainWindow", "clear"))
        self.label.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
